-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 20:52:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema equipmentrentaldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema equipmentrentaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equipmentrentaldb` DEFAULT CHARACTER SET utf8 ;
USE `equipmentrentaldb` ;

-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`Places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`Places` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`Places` (
  `place_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `address` VARCHAR(256) NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`Owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`Owners` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`Owners` (
  `owner_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `place_id` INT NOT NULL,
  `qr_soruce_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`owner_id`),
  INDEX `Places.place_id_idx` (`place_id` ASC) VISIBLE,
  CONSTRAINT `Places.place_id`
    FOREIGN KEY (`place_id`)
    REFERENCES `equipmentrentaldb`.`Places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`EqupmentTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`EqupmentTypes` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`EqupmentTypes` (
  `type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(512) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`Equipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`Equipments` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`Equipments` (
  `equipment_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `owner_id` VARCHAR(64) NOT NULL COMMENT 'このアイテムの登録状態の変更、削除が可能なLINEグループ',
  `picture_path` VARCHAR(256) NULL,
  `status` INT NOT NULL,
  `comment` VARCHAR(500) NULL COMMENT '備品の状態などを記載',
  `equipment_type` INT NOT NULL,
  PRIMARY KEY (`equipment_id`),
  INDEX `Owners.owner_id_idx` (`owner_id` ASC) VISIBLE,
  INDEX `EquipmentTypes.type_id_idx` (`equipment_type` ASC) VISIBLE,
  CONSTRAINT `Facilities.facility_id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `equipmentrentaldb`.`Owners` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EquipmentTypes.type_id`
    FOREIGN KEY (`equipment_type`)
    REFERENCES `equipmentrentaldb`.`EqupmentTypes` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`Events` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`Events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `event_owner_id` VARCHAR(64) NOT NULL,
  `time_from` DATETIME NOT NULL,
  `time_to` DATETIME NOT NULL,
  `comment` VARCHAR(512) NULL,
  `place_id` INT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `Events.place_id_idx` (`place_id` ASC) VISIBLE,
  CONSTRAINT `Events.place_id`
    FOREIGN KEY (`place_id`)
    REFERENCES `equipmentrentaldb`.`Places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`EquipmentReservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`EquipmentReservations` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`EquipmentReservations` (
  `reservation_id` INT NOT NULL,
  `equipment_id` INT NOT NULL,
  `borrower_id` VARCHAR(64) NOT NULL,
  `period_from` DATETIME NOT NULL,
  `period_to` DATETIME NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `EquipmentReservations.equipment_id_idx` (`equipment_id` ASC) VISIBLE,
  INDEX `Events.event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `EquipmentReservations.equipment_id`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `equipmentrentaldb`.`Equipments` (`equipment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Events.event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `equipmentrentaldb`.`Events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`FacilityTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`FacilityTypes` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`FacilityTypes` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(512) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`Facilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`Facilities` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`Facilities` (
  `facility_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `owner_id` VARCHAR(64) NULL,
  `picture_path` VARCHAR(256) NULL,
  `status` INT NULL,
  `comment` VARCHAR(512) NULL,
  `place_id` INT NULL,
  `facility_type` INT NULL,
  PRIMARY KEY (`facility_id`),
  INDEX `Facilities.owner_id_idx` (`owner_id` ASC) VISIBLE,
  INDEX `Places.place_id_idx` (`place_id` ASC) VISIBLE,
  INDEX `FacilityTypes.facility_type_idx` (`facility_type` ASC) VISIBLE,
  CONSTRAINT `Owners.owner_id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `equipmentrentaldb`.`Owners` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Places.place_id`
    FOREIGN KEY (`place_id`)
    REFERENCES `equipmentrentaldb`.`Places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FacilityTypes.facility_type`
    FOREIGN KEY (`facility_type`)
    REFERENCES `equipmentrentaldb`.`FacilityTypes` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipmentrentaldb`.`FacilityReservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipmentrentaldb`.`FacilityReservations` ;

CREATE TABLE IF NOT EXISTS `equipmentrentaldb`.`FacilityReservations` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `facility_id` INT NOT NULL,
  `borrower_id` VARCHAR(64) NOT NULL,
  `event_id` INT NULL,
  `period_from` DATETIME NOT NULL,
  `period_to` DATETIME NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `FacilityReservations.facility_id_idx` (`facility_id` ASC) VISIBLE,
  INDEX `Events.event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `FacilityReservations.facility_id`
    FOREIGN KEY (`facility_id`)
    REFERENCES `equipmentrentaldb`.`Facilities` (`facility_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Events.event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `equipmentrentaldb`.`Events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
